FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.backend.txt .

RUN pip install --no-cache-dir -r requirements.backend.txt

COPY app ./app
COPY scripts ./scripts
COPY data ./data

RUN mkdir -p /app/data/processed

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
