import { useEffect } from "react";

function LegalModal({ isOpen, onClose, type }) {
  // Handle Escape key
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === "Escape" && isOpen) {
        onClose();
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const isTerms = type === "terms";

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal-content legal-modal-content"
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
        aria-labelledby="legal-modal-title"
      >
        {/* Modal Header */}
        <div className="modal-header">
          <div className="modal-title-group">
            <div className="legal-title-badge">
              {isTerms ? "Compliance & Guidelines" : "Data Protection"}
            </div>
            <h2 id="legal-modal-title" className="modal-title">
              {isTerms
                ? "Terms & Conditions — AI-Evolution-Engine"
                : "Privacy Policy — AI-Evolution-Engine"}
            </h2>
            <p className="modal-subtitle">
              Last updated: October 2026 · AIEE Version 1.0
            </p>
          </div>
          <button
            className="modal-close-button"
            onClick={onClose}
            aria-label="Close legal modal"
          >
            ✕
          </button>
        </div>

        {/* Modal Body / Scrollable Content */}
        <div className="modal-body legal-modal-body">
          {isTerms ? (
            <div className="legal-text-wrapper">
              <section className="legal-section">
                <h3>1. Acceptance of Terms</h3>
                <p>
                  By accessing or utilizing the AI-Evolution-Engine (AIEE) dashboard,
                  associated REST APIs, and analysis engines, you agree to comply with
                  and be bound by these Terms and Conditions. If you do not agree to
                  these terms, you must discontinue use of the platform.
                </p>
              </section>

              <section className="legal-section">
                <h3>2. Repository Analysis Scope & Access</h3>
                <p>
                  AIEE performs automated, read-only impact analysis on Git repositories
                  authorized by the user. Analysis comprises commit history inspection,
                  dependency graph generation, KMeans clustering, DBSCAN grouping, and
                  historical co-change frequency evaluation.
                </p>
                <p>
                  AIEE operates with read-only access and never executes arbitrary user
                  code, pushes commits, or modifies remote repositories without explicit
                  instruction.
                </p>
              </section>

              <section className="legal-section">
                <h3>3. Heuristic & Machine Learning Results</h3>
                <p>
                  Change impact scores, risk classifications (High, Medium, Low), and
                  affected-file recommendations generated by AIEE are algorithmic
                  estimations intended to assist developers in test scoping and pull
                  request review. They should be utilized as decision-support insights
                  rather than absolute guarantees of code behavior.
                </p>
              </section>

              <section className="legal-section">
                <h3>4. Authentication & Account Integrity</h3>
                <p>
                  Access to repository analysis features requires authentication via
                  GitHub OAuth 2.0. Users are responsible for safeguarding their GitHub
                  credentials and session tokens. All sessions are bound to secure,
                  encrypted cookies backed by PostgreSQL session records.
                </p>
              </section>

              <section className="legal-section">
                <h3>5. Intellectual Property & Code Ownership</h3>
                <p>
                  Users retain full ownership and intellectual property rights over all
                  source code and repositories analyzed through AIEE. The engine does not
                  claim ownership of your software assets or derivatives.
                </p>
              </section>
            </div>
          ) : (
            <div className="legal-text-wrapper">
              <section className="legal-section">
                <h3>1. Information We Collect</h3>
                <p>
                  When you authenticate with AIEE via GitHub OAuth, we receive
                  basic identity information provided by GitHub, including your GitHub
                  username, avatar URL, and public account identifier. We do not
                  request or store your GitHub account password.
                </p>
              </section>

              <section className="legal-section">
                <h3>2. Repository & Analysis Data Handling</h3>
                <p>
                  When you submit a repository URL for impact analysis, AIEE queries Git
                  metadata, commit logs, and file paths to construct dependency and
                  clustering graphs.
                </p>
                <p>
                  Repository inspection is executed in transient working environments.
                  Your source code is never stored persistently, sold, or shared with
                  third-party entities or commercial model trainers.
                </p>
              </section>

              <section className="legal-section">
                <h3>3. Local Storage & Client Customization</h3>
                <p>
                  To provide a responsive and personalized experience, your custom
                  display name, theme preference (Dark or Light mode), and client-side
                  profile photo are saved locally in your browser’s LocalStorage. This data
                  remains on your device and is not transmitted to external analytics providers.
                </p>
              </section>

              <section className="legal-section">
                <h3>4. Session Security & Cookies</h3>
                <p>
                  AIEE utilizes secure HTTP-only session cookies tied to PostgreSQL session
                  tables to preserve your login status across navigation. These cookies
                  cannot be accessed by third-party scripts and expire automatically upon
                  logout.
                </p>
              </section>

              <section className="legal-section">
                <h3>5. Data Rights & Inquiries</h3>
                <p>
                  You may disconnect your GitHub account and terminate active sessions at
                  any time using the Logout option in the dashboard profile menu. For any
                  inquiries regarding data management or engine functionality, contact the
                  AIEE engineering team.
                </p>
              </section>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="modal-footer">
          <button type="button" className="btn-primary" onClick={onClose}>
            I Understand
          </button>
        </div>
      </div>
    </div>
  );
}

export default LegalModal;
